# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: master
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"

  # Maintain dependencies for NuGet packages
  - package-ecosystem: "nuget"
    directory: "/"
    target-branch: master
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
