CREATE TABLE [dbo].[Categories]
(
	[Id] UNIQUEIDENTIFIER NOT NULL
		CONSTRAINT [PK_Categories] PRIMARY KEY CLUSTERED
		CONSTRAINT [DF_Categories_Id] DEFAULT NEWSEQUENTIALID(),
	[Name] NVARCHAR(100) NOT NULL
		CONSTRAINT [UQ_Categories_Name] UNIQUE
		(
			[Name] ASC
		) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
) ON [PRIMARY];

CREATE TABLE [dbo].[SubCategories]
(
	[Id] UNIQUEIDENTIFIER NOT NULL
		CONSTRAINT [PK_SubCategories] PRIMARY KEY CLUSTERED
		CONSTRAINT [DF_SubCategories_Id] DEFAULT NEWSEQUENTIALID(),
	[CategoryId] UNIQUEIDENTIFIER NOT NULL
		CONSTRAINT [FK_SubCategories_Categories] REFERENCES [dbo].[Categories] ([Id]) ON DELETE CASCADE,
	[Name] NVARCHAR(100) NOT NULL
		CONSTRAINT [UQ_Categories_CategoryId_Name] UNIQUE
		(
			[CategoryId] ASC,
			[Name] ASC
		) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
) ON [PRIMARY];

CREATE TABLE [dbo].[Events]
(
	[Id] UNIQUEIDENTIFIER NOT NULL
		CONSTRAINT [PK_Events] PRIMARY KEY CLUSTERED
		CONSTRAINT [DF_Events_Id] DEFAULT NEWSEQUENTIALID(),
	[Title] NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(4000) NULL,
	[Address] NVARCHAR(255) NOT NULL,
	[Location] GEOGRAPHY NOT NULL,
	[StartDateTime] DATETIME2 NOT NULL,
	[EndDateTime] DATETIME2 NULL,
	[CategoryId] UNIQUEIDENTIFIER NOT NULL
		CONSTRAINT [FK_Events_Categories] REFERENCES [dbo].[Categories] ([Id]),
	[SubCategoryId] UNIQUEIDENTIFIER NOT NULL
		CONSTRAINT [FK_Events_SubCategories] REFERENCES [dbo].[SubCategories] ([Id]) ON DELETE CASCADE,
	[MaxParticipants] INT NULL,
	[PasswordHash] NVARCHAR(MAX) NULL,
) ON [PRIMARY];

CREATE TABLE [dbo].[EventsOwners]
(
	[EventId] UNIQUEIDENTIFIER
		CONSTRAINT [FK_EventsOwners_Events] REFERENCES [dbo].[Events] ([Id]) ON DELETE CASCADE,
	[OwnerId] UNIQUEIDENTIFIER
		CONSTRAINT [FK_EventsOwners_Users] REFERENCES [dbo].[Users] ([Id]) ON DELETE CASCADE,
	CONSTRAINT [PK_EventsOwners] PRIMARY KEY CLUSTERED ([OwnerId], [EventId])
);

CREATE TABLE [dbo].[EventsParticipants]
(
	[EventId] UNIQUEIDENTIFIER
		CONSTRAINT [FK_EventsParticipants_Events] REFERENCES [dbo].[Events] ([Id]) ON DELETE CASCADE,
	[ParticipantId] UNIQUEIDENTIFIER
		CONSTRAINT [FK_EventsParticipants_Users] REFERENCES [dbo].[Users] ([Id]) ON DELETE CASCADE,
	CONSTRAINT [PK_EventsParticipants] PRIMARY KEY CLUSTERED ([ParticipantId], [EventId])
);