version: '3.8'

services:
  socialeventmanager.api:
    build:
      context: .
      dockerfile: src/SocialEventManager.API/Dockerfile
    ports:
      - '8080:80'
    networks:
      - aspnet
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__0=redis-master:6379?password=${REDIS_MASTER_PASSWORD}
      - Redis__1=redis-replica:6379?password=${REDIS_REPLICA_PASSWORD}
      - Redis__2=redis-replica:6379?password=${REDIS_REPLICA_PASSWORD}
      - Redis__3=redis-replica:6379?password=${REDIS_REPLICA_PASSWORD}
    depends_on:
      - seq-analysis
      - sql-server-database 
      - redis-master

  seq-analysis:
    image: datalust/seq
    ports:
      - '8005:80'
    networks:
      - aspnet
    environment:
      - ACCEPT_EULA=Y

  sql-server-database:
    container_name: sql-server-database
    build:
      context: .
      dockerfile: items/sql/sql.Dockerfile
    restart: always
    ports:
      - '1440:1433'
    networks:
      - aspnet
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
      - ASPNETCORE_ENVIRONMENT=Development
      - SA_PASSWORD=${SA_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ConnectionStrings__SocialEventManager=${ConnectionStrings__SocialEventManager}
      - ConnectionStrings__SocialEventManagerHangfire=${ConnectionStrings__SocialEventManagerHangfire}
      - ConnectionStrings__SocialEventManagerTest=${ConnectionStrings__SocialEventManagerTest}

  redis-master:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    networks:
      - aspnet
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=${REDIS_MASTER_PASSWORD}
    volumes:
      - ./data/redis:/bitnami
      - ./data/redis/conf/redis.conf:/opt/bitnami/redis/conf/redis.conf

  redis-replica:
    image: 'bitnami/redis:latest'
    ports:
      - '6380-6382:6379'
    depends_on:
      - redis-master
    networks:
      - aspnet
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=${REDIS_MASTER_PASSWORD}
      - REDIS_PASSWORD=${REDIS_REPLICA_PASSWORD}
    deploy:
      replicas: 3

  socialeventmanager.tests:
    container_name: socialeventmanager.tests
    image: mcr.microsoft.com/dotnet/sdk:6.0
    networks:
      - aspnet
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__0=redis-master:6379?password=${REDIS_MASTER_PASSWORD}
      - Redis__1=redis-replica:6379?password=${REDIS_REPLICA_PASSWORD}
      - Redis__2=redis-replica:6379?password=${REDIS_REPLICA_PASSWORD}
      - Redis__3=redis-replica:6379?password=${REDIS_REPLICA_PASSWORD}
    volumes:
      - .:/home/runner/work/social-event-manager/social-event-manager/SocialEventManager
      - .:/tests
    working_dir: /home/runner/work/social-event-manager/social-event-manager/SocialEventManager
    command:
      [
        'dotnet',
        'test',
        'tests/SocialEventManager.Tests/SocialEventManager.Tests.csproj',
        '/p:CollectCoverage=true',
        '/p:CoverletOutputFormat=lcov'
      ]
    depends_on:
      - sql-server-database
      - redis-master
      - redis-replica

networks:
  aspnet:
    driver: bridge