version: '3.8'

services:
  socialeventmanager.api:
    build:
      context: .
      dockerfile: src/SocialEventManager.API/Dockerfile
    ports:
      - '8080:80'
    networks:
      - aspnet
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis__0=redis-master:6379
      - Redis__1=redis-replica:6379
    depends_on:
      - seq-analysis
      - sql-server-database 
      - redis-master

  seq-analysis:
    image: datalust/seq
    ports:
      - '8005:80'
    networks:
      - aspnet
    environment:
      - ACCEPT_EULA=Y

  sql-server-database:
    container_name: sql-server-database
    build:
      context: .
      dockerfile: items/sql/sql.Dockerfile
    restart: always
    ports:
      - '1440:1433'
    networks:
      - aspnet
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
      - ASPNETCORE_ENVIRONMENT=Development
      - SA_PASSWORD=${SA_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ConnectionStrings__SocialEventManager=${ConnectionStrings__SocialEventManager}
      - ConnectionStrings__SocialEventManagerHangfire=${ConnectionStrings__SocialEventManagerHangfire}
      - ConnectionStrings__SocialEventManagerTest=${ConnectionStrings__SocialEventManagerTest}

  redis-master:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    networks:
      - aspnet
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data/redis:/bitnami
      - ./data/redis/conf/redis.conf:/opt/bitnami/redis/conf/redis.conf

  redis-replica:
    image: 'bitnami/redis:latest'
    ports:
      - '6380:6379'
    depends_on:
      - redis-master
    networks:
      - aspnet
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes
    deploy:
      replicas: 1


  socialeventmanager.tests:
    container_name: socialeventmanager.tests
    image: mcr.microsoft.com/dotnet/sdk:5.0
    networks:
      - aspnet
    env_file:
      - .env
    volumes:
      - .:/src
      - .:/tests
    working_dir: /src
    command:
      [
        '/bin/bash',
        'items/sql/wait-for-it.sh',
        'sql-server-database:1433',
        '--',
        'dotnet',
        'test',
        'tests/SocialEventManager.Tests/SocialEventManager.Tests.csproj'
      ]
    depends_on:
      - sql-server-database

networks:
  aspnet:
    driver: bridge