name: Continuous Integration and Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code 🛎
      uses: actions/checkout@v3
      
    - name: Setup .NET 🔧
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies 🛠
      working-directory: ./SocialEventManager/src/SocialEventManager.API
      run: dotnet restore
      
    - name: Build app 🚀
      working-directory: ./SocialEventManager/src/SocialEventManager.API
      run: dotnet build --configuration Release --no-restore
      
    - name: Run Tests 🧪
      working-directory: ./SocialEventManager
      run: docker-compose up --exit-code-from socialeventmanager.tests socialeventmanager.tests
      env:
        SA_PASSWORD: ${{ secrets.SA_PASSWORD }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_USER: ${{ secrets.DB_USER }}
        ConnectionStrings__SocialEventManager: ${{ secrets.ConnectionStrings__SocialEventManager }}
        ConnectionStrings__SocialEventManagerHangfire: ${{ secrets.ConnectionStrings__SocialEventManagerHangfire }}
        ConnectionStrings__SocialEventManagerTest: ${{ secrets.ConnectionStrings__SocialEventManagerTest }}
        REDIS_MASTER_PASSWORD: ${{ secrets.REDIS_MASTER_PASSWORD }}
        REDIS_REPLICA_PASSWORD: ${{ secrets.REDIS_REPLICA_PASSWORD }}